### ISSUE TITLE
"template?.Parameters[i].Name" returns null

### ISSUE THREAD

**Issue by SKmaric** [Radfordhound/HedgeLib#7] opened 2017-07-11 02:17 UTC
For example in [line 204 of SetData.cs](https://github.com/Radfordhound/HedgeLib/blob/master/HedgeLib/Sets/SetData.cs#L204). As such when using the ExportXML module (such as through [Sonic Colors Set Editor](https://github.com/thesupersonic16/Sonic-Colors-Set-Editor)) all of the parameter elements in the outputted file are simply named "Parameter" instead of the correct respective names:

    <Parameters>
      <Parameter type="UInt32">0</Parameter>
      <Parameter type="Boolean">True</Parameter>
      <Parameter type="Boolean">False</Parameter>
      <Parameter type="Boolean">False</Parameter>
      <Parameter type="Boolean">False</Parameter>
    </Parameters>

**Comment by thesupersonic16** [comment] 2017-07-11 03:17
Oh, Did I test the export function? I don't remember it doing that.

**Comment by thesupersonic16** [comment] 2017-07-11 03:23
Thanks writing this, The problem is on [Sonic Colors Set Editor](https://github.com/thesupersonic16/Sonic-Colors-Set-Editor), Its null because I forgot to pass the templates for exporting the xml files.

**Comment by Radfordhound** [comment] 2017-07-11 03:25
Welp since the issue seems to not be on HedgeLib's end I'll close the issue. Feel free to re-open it if necessary!

**Closed by Radfordhound** 2017-07-11 03:25 UTC

**Comment by SKmaric** [comment] 2017-07-11 06:59
Ah, alright then. I fiddled around a bit with the Set Editor and its export function, followed by the aforementioned cs file, trying to solve it myself, and I figured it was within HedgeLib that was causing the issue. Thanks for the quick response!

**Comment by thesupersonic16** [comment] 2017-07-11 08:32
Looks like it will call them all "Parameter" if templates is null, which is null by default unless you pass them.

**Comment by Radfordhound** [comment] 2017-07-11 20:07
Yup! This is by design, since there's no real way HedgeLib could come up with param names that are much better without templates.
